#!/usr/bin/python3
raise Exception("fail!")